site_name: David Clarke, Physicist 
site_url: https://clarkedavida.github.io/
theme:
    name: material
nav:
    - Home: index.md
    - Teaching: teaching.md
    - Research: research.md
    - Learning: learning.md
    - Outreach: outreach.md
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/dclarkephysics
    - icon: fontawesome/brands/github
      link: https://github.com/clarkedavida
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/dclarkephysics
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/David-Clarke-47
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-5570-0894 
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
